openapi: 3.0.1
info:
  title: OAuth Proxy
  description: |
    A simple service that acts as a proxy for Keycloak SSO Transfer flow implementations exposing OAuth2-compliant API
  version: 0.1.0
servers:
  - url: /
paths:
  /oauth/token:
    get:
      tags:
        - oauth
      summary: Obtain redirect to Keycloak login page to enter user credentials
      parameters:
        - name: client_id
          in: query
          description: Unique identificator of backend application
          schema:
            type: string
          required: true
      responses:
        302:
          description: "302 response"
          headers:
            Location:
              description: Page where the client can enter his username and password to get access token.
              schema:
                type: string
                format: uri
    post:
      tags:
        - oauth
      summary: Refresh access token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                grant_type:
                  type: string
                  default: refresh_token
                  enum:
                    - refresh_token
                refresh_token:
                  type: string
              required:
                - client_id
                - grant_type
                - refresh_token
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
                  refresh_expires_in:
                    type: integer
