apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-app-config
data:
  backend-app-config.json: |
    {
      "server": {
        "host": "0.0.0.0",
        "port": 9377
      },

      "identityServer": {
        "url": "http://keycloak.192.168.99.100.nip.io",
        "resources": {
          "userinfo": "/auth/realms/gryphon/protocol/openid-connect/userinfo"
        }
      }
    }
