apiVersion: v1
kind: Service
metadata:
  name: authorizer-service
  labels:
    app: authorizer
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  selector:
    app: authorizer
