apiVersion: v1
kind: ConfigMap
metadata:
  name: authorizer-config
data:
  authorizer-config.json: |
    {
      "server": {
        "host": "0.0.0.0",
        "port": 9376
      },

      "authorizer": {
        "url": "http://gryphon.192.168.99.100.nip.io"
      },

      "identityServer": {
        "url": "http://keycloak.192.168.99.100.nip.io",
        "resources": {
          "identifier": "/auth/realms/gryphon",
          "refreshToken": "/auth/realms/gryphon/protocol/openid-connect/token"
        }
      }
    }
